### ISSUE TITLE
ngcc fails when upgraded angular 9.0.0-rc.3 to 9.0.0-rc.4

### ISSUE THREAD

**Issue by vecernik** [angular/flex-layout#1156]
When upgraded from angular 9.0.0-rc.3 to 9.0.0-rc.4, ngcc fails with following error:
```
$ ngcc --properties es2015 browser module main --first-only --create-ivy-entry-point
Compiling @angular/flex-layout/extended : es2015 as esm2015
Error: Error on worker #6: Error: Failed to compile entry-point @angular/platform-server due to compilation errors:
node_modules/@angular/common/http/http.d.ts(2801,22): error TS-996002: Appears in the NgModule.imports of ServerModule, but could not be resolved to an NgModule class

    at ClusterWorker.compile (/my-project/node_modules/@angular/compiler-cli/ngcc/src/main.js:170:27)
    at Worker.<anonymous> (/my-project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:41:42)
    at Worker.emit (events.js:210:5)
    at process.<anonymous> (internal/cluster/worker.js:34:12)
    at process.emit (events.js:210:5)
    at emit (internal/child_process.js:878:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
    at ClusterMaster.onWorkerMessage (/my-project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:158:27)
    at /my-project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:46:95
    at ClusterMaster.<anonymous> (/my-project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:238:57)
    at step (/my-project/node_modules/tslib/tslib.js:136:27)
    at Object.next (/my-project/node_modules/tslib/tslib.js:117:57)
    at /my-project/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/my-project/node_modules/tslib/tslib.js:106:16)
    at EventEmitter.<anonymous> (/my-project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:232:32)
    at EventEmitter.emit (events.js:210:5)
Compiling @angular/flex-layout/flex : es2015 as esm2015
Compiling @angular/flex-layout/grid : es2015 as esm2015
```

**Comment by jpike88** [comment]
works fine on angular 9.0.0-rc6, fusebox bundler. is it still an issue with ngcc?

**Comment by CaerusKaru** [comment]
@vecernik Can you confirm this is still an issue?

**Comment by vecernik** [comment]
it's been fixed in angular 9.0.0-rc.6
