### ISSUE TITLE
Custom breakpoints - Cannot read property 'mediaQuery' of undefined error

### ISSUE THREAD

**Issue by nivram80** [angular/flex-layout#262]
I'm trying to create my own custom breakpoints. Using the [doc](https://github.com/angular/flex-layout/wiki/Custom-Breakpoints) as a reference, I get a `Cannot read property 'mediaQuery' of undefined` error.

I'm overriding the default breakpoints in the `custom-breakpoints.component.ts` file and using it in the `custom-breakpoints.module.ts` which is then being imported into the app via the `test-app.module.ts` file.

Here is a [plunker](http://plnkr.co/edit/8KN69A?p=preview) that shows what I'm trying to do.

**Comment by lvanngo** [comment]
Try the latest version: 2.0.0-beta.8.  At least the error is gone.  I'm trying this out too.

**Comment by lvanngo** [comment]
Forgot to say, be sure to modify the code to return DEFAULT_BREAKPOINTS after the map function call since map returns nothing.

**Comment by lvanngo** [comment]
Update: Every time I overwrote the BREAKPOINTS provider successfully, none of the Directives seem to work and the breakpoints are not triggered at all.  Not sure why...  I think we have to wait until this feature is retested and documents updated.

**Comment by alexfung888** [comment]
@lvanngo 
in your switch statement, add the suffix:
```
  const they: BreakPoint[] = DEFAULT_BREAKPOINTS
    .map((it: BreakPoint) => {
      switch (it.alias) {
        case 'xs' :
          it.mediaQuery =  `(max-width: ${smMin - 1}px)`;
          it.suffix = 'Xs';
          break;
        case 'gt-xs' :
          it.mediaQuery =  `(min-width: ${smMin}px)`;
          it.suffix = 'GtXs';
          break;
```
Since beta 7, the DEFAULT_BREAKPOINTS lost all the suffix members. Add them back and all the dynamic API will work properly.

However, I still can't use beta 8 at all. It always get
`TypeError: _this._renderer.setStyle is not a function`

**Comment by ThomasBurleson** [comment]
@alexfung888 - Beta.8 requires Angular 4.1 or higher due to AOT requirements.

**Comment by ThomasBurleson** [comment]
@lvanngo - your map iterator must return the breakpoint:

```js
import { BreakPoint, DEFAULT_BREAKPOINTS } from '@angular/flex-layout';

const CUSTOM = {
  'xs'    : 'screen and (max-width: 599px)',
  'gt-xs' : 'screen and (min-width: 600px)',
  'sm'    : 'screen and (min-width: 600px) and (max-width: 1023px)',
  'gt-sm' : 'screen and (min-width: 1024px)', 
  'md'    : 'screen and (min-width: 1024px) and (max-width: 1440px)',
  'gt-md' : 'screen and (min-width: 1440px)',
  'lg'    : 'screen and (min-width: 1440px) and (max-width: 1919px)',
  'gt-lg' : 'screen and (min-width: 1920px)',
  'xl'    : 'screen and (min-width: 1920px) and (max-width: 5000px)',
}

function updateMediaQuery(it:BreakPoint) {
  let mq = CUSTOM[ it.alias ];
  if ( !!mq ) {
    it.mediaQuery = mq;  
  }
  return it;
}

export function customBreakPoints() {
  
  return DEFAULT_BREAKPOINTS.map((it:BreakPoint) => updateMediaQuery);
}
```

This appears to be working now. See [Plunkr Demo](http://plnkr.co/edit/0EXenG?p=preview)

**Comment by ThomasBurleson** [comment]
Closing as not-an-issue.

**Comment by ThomasBurleson** [comment]
@alexfung888 

Now custom suffices are generated based on breakpoint aliases: [validateSuffices()](https://github.com/angular/flex-layout/blob/master/src/lib/utils/breakpoint-tools.ts#L35-L42)

```js
/**
 *  Ensure that only a single global BreakPoint list is instantiated...
 */
export function DEFAULT_BREAKPOINTS_PROVIDER_FACTORY() {
  return validateSuffixes(DEFAULT_BREAKPOINTS);
}
```

For @lvanngo - who just modified the default breakpoints - this is sufficient.
To add more/extra custom breakpoints - that will merge with the default list - developers should use 
the 

* [CUSTOM_BREAKPOINTS_PROVIDER_FACTORY](https://github.com/angular/flex-layout/blob/master/src/lib/media-query/breakpoints/break-points-provider.ts#L79-L85)
* Consult [Custom Breakpoints Example](https://github.com/angular/flex-layout/blob/master/src/lib/media-query/breakpoints/data/orientation-break-points.spec.ts#L53-L61) for details.

**Comment by alexfung888** [comment]
Thanks @ThomasBurleson 
Yes I am still at core@4.0.3 No wonder beta8 failed miserably.
I guess the CUSTOM_BREAKPOINTS_PROVIDER_FACTORY code above only works for beta8.
On beta7, nothing happens. No media change is reported at all.

BTW, I changed your sample code to read as follows, which I think is much easier to modify

```
const smMin = 600;
const mdMin = 1024;
const lgMin = 1280;
const xlMin = 1920;

const CUSTOM = {
  'xs'    : `screen and (max-width: ${smMin - 1})`,
  'gt-xs' : `screen and (min-width: ${smMin})`,
  'sm'    : `screen and (min-width: ${smMin}) and (max-width: ${mdMin - 1})`,
  'gt-sm' : `screen and (min-width: ${mdMin})`,
  'md'    : `screen and (min-width: ${mdMin}) and (max-width: ${lgMin - 1})`,
  'gt-md' : `screen and (min-width: ${lgMin})`,
  'lg'    : `screen and (min-width: ${lgMin}) and (max-width: ${xlMin - 1})`,
  'gt-lg' : `screen and (min-width: ${xlMin})`,
  'xl'    : `screen and (min-width: ${xlMin}) and (max-width: 5000px)`,
}
```

**Comment by ThomasBurleson** [comment]
@alexfung888 - The custom breakpoint features are also available in beta.7. 

> I updated the [WIKI](https://github.com/angular/flex-layout/wiki/Custom-Breakpoints) (again) to show the correct defaults and imports.

**Comment by alexfung888** [comment]
Found my problem. Look at my code above: I have forgotten to include "px" in the media detection!

On the other hand, I still cannot get @angular/material 2.0.0-beta.3 to work. I am now on latest of core, CLI, material, flex-layout. I am getting 

`TypeError: _this._renderer.setStyle is not a function`

every time.

**Comment by alexfung888** [comment]
@ThomasBurleson I have updated to angular/core 4.1.0, materal 2.0.0-beta.3
my code works fine on flex-layout@2.0.0-beta.7
but
`TypeError: _this._renderer.setStyle is not a function`
on flex-layout@2.0.0-beta.8
any suggestions on how to troubleshoot it?

**Comment by ThomasBurleson** [comment]
@alexeagle - 
* delete your `node-modules` folder.
* reinstall with `npm install`. 

> Make sure you are using Angular 4.1 or higher.

**Comment by alexeagle** [comment]
@alexfung888 ^

**Comment by alexfung888** [comment]
@ThomasBurleson 
I copy all the source files to a new directory without the node-modules. Do an npm install.
angular/core etc is 410
material is 200beta3
cli is 101
flex-layout is 200beta8
and the new folder (when ng serve) crashes when started. 
the original folder is 200beta7 is running fine.

**Comment by ThomasBurleson** [comment]
@alexfung888 - open a new issue please. Can you provide a zip that reproduces this? I will debug locally.

**Comment by alexfung888** [comment]
Thanks. I'll try to cut down to code to see when it starts to work.

**Comment by alexfung888** [comment]
@ThomasBurleson 
created issue #270
