### ISSUE TITLE
Error thrown combining fxLayoutAlign with fxFlex using box syntax

### ISSUE THREAD

**Issue by jfcere** [angular/flex-layout#1089]
# Bug Report

When using _banana-box_ syntax and combining `[fxLayoutAlign]` with `[fxFlex]` with responsive API, reevaluation of flex directives when resizing throws `Error: basis.indexOf is not a function` if `[fxFlex]` value type is `number`.

#### What is the expected behavior?

`[fxFlex]` value type `number` to be evaluated without throwing when combined with `[fxLayoutAlign]`.

#### What is the current behavior?

Error `Error: basis.indexOf is not a function` is thrown when `[fxFlex]` value type is `number` when combined with `[fxLayoutAlign]` and directive is reevaluated due to the use of responsive API.

#### What are the steps to reproduce?

Follow the StackBlitz examples below, and resize the window until layout changes from _row_ to _column_ and lookout for `Error: basis.indexOf is not a function` error in the console.

```html
<!-- concerned code used in the example -->
<div [fxLayoutAlign]="'end'" [fxFlex]="100">
    third-section
</div>
```

The error is not thrown using @angular/flex-layout v7.0.0-beta23:
https://stackblitz.com/edit/angular-flex-issue-v700-beta23

The error is thrown using @angular/flex-layout v7.0.0-beta24 and up:
https://stackblitz.com/edit/angular-flex-issue-v700-beta24
https://stackblitz.com/edit/angular-flex-issue-v800-beta26

#### What is the use-case or motivation for changing an existing behavior?

Fix the error happening and enforce consistency as `[fxFlex]` used alone with value type `number` is correctly evaluated and works as expected.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

- Angular 7 with @angular/flex-layout v7.0.0-beta24
- Angular 8 with @angular/flex-layout v8.0.0-beta26

#### Is there anything else we should know?

The error is not happening if we do not use the _banana-box_ syntax but it was working in @angular/flex-layout v7.0.0-beta.23.

If we change `[fxFlex]="100"` to `[fxFlex]="'100'"` to specify that value is a `string` the error goes away but note that it previously worked without the quotes (and still is if not combined with `fxLayoutAlign`) and resolved as a percent value.

The error comes from `validateBasis` function at _line 17_ because the `basis` value type is `number` instead of `string` and therefore `indexOf` is not available:

https://github.com/angular/flex-layout/blob/28bc2ae7476367f111edfce39a05b3f9041501f7/src/lib/core/basis-validator/basis-validator.ts#L14-L35

**Comment by CaerusKaru** [comment]
Oh this is nasty. This actually only happens when we explicitly trigger the reflow. Otherwise it works correctly. I'll get a patch in soon.

**Comment by CaerusKaru** [comment]
Also, this only gets triggered because you have an `fxLayoutAlign` on the same element, which triggers the faulty method. Again, nasty.

**Comment by CaerusKaru** [comment]
@jfcere Please confirm this is fixed in the latest version of the nightly builds once they get published.

**Comment by jfcere** [comment]
@CaerusKaru I will, but 8.0.0-beta.27 is still not published

**Comment by CaerusKaru** [comment]
@jfcere The nightly builds are not published to NPM, they’re published to a GitHub repo called angular/flex-layout-builds
