### ISSUE TITLE
has no exported member 'ɵNgClassImpl'

### ISSUE THREAD

**Issue by kac89** [angular/flex-layout#1064]
Hi there,

I have issues on build:

ERROR in node_modules/@angular/flex-layout/extended/typings/class/class.d.ts(9,19): error TS2305: Module '"XXX/node_modules/@angular/common/common"' has no exported member 'ɵNgClassImpl'.
node_modules/@angular/flex-layout/extended/typings/class/class.d.ts(9,33): error TS2305: Module '"XXX/node_modules/@angular/common/common"' has no exported member 'ɵNgClassR2Impl'.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(9,19): error TS2305: Module '"XXX/node_modules/@angular/common/common"' has no exported member 'ɵNgStyleImpl'.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(9,33): error TS2305: Module '"XXX/node_modules/@angular/common/common"' has no exported member 'ɵNgStyleR2Impl'.

 "dependencies": {
    "@angular/animations": "^7.0.4",
    "@angular/cdk": "^7.1.0",
    "@angular/common": "^7.0.4",
    "@angular/compiler": "^7.0.4",
    "@angular/core": "^7.0.4",
    "@angular/flex-layout": "github:angular/flex-layout-builds",
    "@angular/forms": "^7.0.4",
    "@angular/http": "^7.0.4",
    "@angular/material": "^7.1.0",
    "@angular/platform-browser": "^7.0.4",
    "@angular/platform-browser-dynamic": "^7.0.4",
    "@angular/router": "^7.0.4",
    "clone": "^2.1.2",
    "core-js": "^2.5.4",
    "crypto-js": "^3.1.9-1",
    "gulp-clone": "^2.0.1",
    "hammerjs": "^2.0.8",
    "ng2-charts": "^1.6.0",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.3.3",
    "zone.js": "~0.8.26"
  },

Any one have some advice ?

**Comment by kac89** [comment]
fix:
npm install @angular/flex-layout@7.0.0-beta.24

**Comment by zensarCompass** [comment]
Works for me

**Comment by saanplus** [comment]
thanks. works for me.

**Comment by CaerusKaru** [comment]
Your issue is that Flex Layout v8 only works with Angular v8, just like Components and CLI. It has been this way always.

**Comment by samuel-lf** [comment]
Thanks, works for me!

**Comment by Shreyanshnit19** [comment]
Thanks , works for me also !

**Comment by owolabiezekiel** [comment]
how do I go back to the version 7 of angular flex layout?

**Comment by Polyterative** [comment]
@owolabiezekiel go back to ` @angular/flex-layout@7.0.0-beta.24`

**Comment by Enngage** [comment]
@CaerusKaru, it doesn't seem to work with Angular 8 & Material 8 with latest release. I just did clean install (deleted node_modules, removed package-lock) for:

```Angular CLI: 8.0.0-rc.4
Node: 10.15.3
OS: win32 x64
Angular: 8.0.0-rc.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.800.0-rc.4
@angular-devkit/build-angular              0.800.0-rc.4
@angular-devkit/build-optimizer            0.800.0-rc.4
@angular-devkit/build-webpack              0.800.0-rc.4
@angular-devkit/core                       8.0.0-rc.4
@angular-devkit/schematics                 8.0.0-rc.4
@angular/cdk                               8.0.0-rc.1
@angular/cli                               8.0.0-rc.4
@angular/flex-layout                       8.0.0-beta.25
@angular/material                          8.0.0-rc.1
@ngtools/webpack                           8.0.0-rc.4
@nguniversal/common                        7.1.1
@nguniversal/express-engine                7.1.1
@nguniversal/module-map-ngfactory-loader   7.1.1
@schematics/angular                        8.0.0-rc.4
@schematics/update                         0.800.0-rc.4
rxjs                                       6.5.2
typescript                                 3.4.5
webpack                                    4.30.0
```

And got the following for `ng serve`: 

```ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 1256:52-69
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/grid.es5.js 40:63-80
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/grid.es5.js 356:67-84
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/grid.es5.js 514:62-79
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/grid.es5.js 605:62-79
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/grid.es5.js 730:62-79
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/grid.es5.js 845:64-81
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/grid.es5.js 947:65-82
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/grid.es5.js 1068:61-78
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/grid.es5.js 1184:61-78
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/grid.es5.js 1286:62-79
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/flex.es5.js 140:60-77
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/flex.es5.js 275:63-80
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 3658:57-74
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/flex.es5.js 806:58-75
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 3042:52-69
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/flex.es5.js 1023:63-80
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/flex.es5.js 1120:64-81
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/flex.es5.js 1270:63-80
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/flex.es5.js 1358:62-79
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/flex.es5.js 1485:65-82
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/extended.es5.js 39:60-77
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/extended.es5.js 299:62-79
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 205:55-72
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 1057:60-77
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 2654:54-71
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/grid.es5.js 176:70-87
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 2348:55-72
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 2025:51-68
"export 'ΔdefineInjectable' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 2654:191-198
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 1256:174-181
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 2025:132-139
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 2025:161-168
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 1256:135-142
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 2348:144-151
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 2348:173-180
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 2348:194-201
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 1057:159-166
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 2654:141-148
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 2654:170-177
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 1256:152-159
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 2654:215-222
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 2654:237-244
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/flex.es5.js 806:153-160
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 3042:135-142
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 3042:162-169
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 3042:188-195
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 3042:210-217
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/flex.es5.js 275:168-175
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 3658:150-157
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 3658:171-178
"export 'Δinject' was not found in '@angular/core'
ERROR in ./node_modules/@angular/flex-layout/esm5/core.es5.js 3658:200-207
"export 'Δinject' was not found in '@angular/core'`

**Comment by ganySA** [comment]
Seems to break with angular 8 RC 5.

**Comment by vis-8757** [comment]
@kac89  that command gives the following error for me 

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular/flex-layout@7.0.0-beta2.4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

what do you suggest now ??  :|

**Comment by CaerusKaru** [comment]
@vis-8757 `@angular/flex-layout@7.0.0-beta2.4 -> @angular/flex-layout@7.0.0-beta.24`?

**Comment by vis-8757** [comment]
> @vis-8757 @angular/flex-layout@7.0.0-beta2.4 -> @angular/flex-layout@7.0.0-beta.24?

yes. that was it ! Thanks ! :)

**Comment by Splaktar** [comment]
@Enngage fixed in https://github.com/angular/flex-layout/pull/1068.

**Comment by rhinocerous** [comment]
I set up a brand new project yesterday using the latest and greatest of everything I could find. I've used FlexLayout before on other projects and it's awesome, I want to use it in this one too, but unfortunately I am getting the same errors with the newest version (8.0.1) and Angular Material. I considered just reverting back to v8.0.0 , in which case 8.0.0-beta.26 should theoretically work, but I wasn't able to get it working. I had to jump through some hoops as described here: to get Angular Material running so I am kind of stuck with 8.0.1.

My package.json looks like this:
`  "dependencies": {
    "@angular/animations": "^7.2.15",
    "@angular/cdk": "^8.0.1",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "^8.0.1",
    "@angular/flex-layout": "^8.0.0-beta.26",
    "@angular/forms": "~7.2.0",
    "@angular/material": "^8.0.1",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },`

The errors I get when I try to add FlexLayoutModule to my app.module.ts:

`ERROR in node_modules/@angular/flex-layout/extended/typings/class/class.d.ts(9,19): error TS2305: Module '"C:/gitlab/rpm.art/rpm-art/node_modules/@angular/common/common"' has no exported member 'ɵNgClassImpl'.
node_modules/@angular/flex-layout/extended/typings/class/class.d.ts(9,33): error TS2305: Module '"C:/gitlab/rpm.art/rpm-art/node_modules/@angular/common/common"' has no exported member 'ɵNgClassR2Impl'.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(9,19): error TS2305: Module '"C:/gitlab/rpm.art/rpm-art/node_modules/@angular/common/common"' has no exported member 'ɵNgStyleImpl'.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(9,33): error TS2305: Module '"C:/gitlab/rpm.art/rpm-art/node_modules/@angular/common/common"' has no exported member 'ɵNgStyleR2Impl'.`

There are only four errors so it seems like it should be easy to fix but I am not sure where to start. In looking at the source it seems like those dependencies from @angular/common got renamed or moved but I can't find any further info on it on the gogle. 

Anybody have any suggestions on how I could get it working on v8.0.1? Sorry if I am missing something obvious....

**Comment by Splaktar** [comment]
@rhinocerous I would suggest running `ng update @angular/core` since those dependencies are still on Angular version 7.

**Comment by reviloera** [comment]
> @rhinocerous I would suggest running `ng update @angular/core` since those dependencies are still on Angular version 7.
this one solved my problem .. thanks

**Comment by rhinocerous** [comment]
@Splaktar it of course works perfectly after doing that. Thank you for taking the time to answer such a silly question, I appreciate the assist.
