### ISSUE TITLE
[resolved] RxJS 6.3.0 breaks angular flex layout

### ISSUE THREAD

**Issue by skiabox** [angular/flex-layout#827]
I just tried to use rxjs 6.3.0 and it seems that it breaks angular flex-layout so I returned to RxJS 6.2.2

**Comment by bhundven** [comment]
```ERROR in node_modules/@angular/flex-layout/core/typings/observable-media/observable-media.d.ts(11,14): error TS2416: Property 'subscribe' in type 'ObservableMedia' is not assignable to the same property in base type 'Subscribable<MediaChange>'.
  Type '(next?: (value: MediaChange) => void, error?: (error: any) => void, complete?: () => void) => Sub...' is not assignable to type '{ (observer?: PartialObserver<MediaChange>): Unsubscribable; (next?: (value: MediaChange) => void...'.
    Types of parameters 'next' and 'observer' are incompatible.
      Type 'PartialObserver<MediaChange>' is not assignable to type '(value: MediaChange) => void'.
        Type 'NextObserver<MediaChange>' is not assignable to type '(value: MediaChange) => void'.
          Type 'NextObserver<MediaChange>' provides no match for the signature '(value: MediaChange): void'.```

Same, also reverted to 6.2.2 to fix the build.

**Comment by lexcaraig** [comment]
@skiabox what version of `@angular/flex-layout` are you using? Bec, I'm getting the same error. Thanks.

**Comment by CaerusKaru** [comment]
So here's the rub: RxJS v6.3 introduced a change to the `Subscribable` interface, which is what `ObservableMedia` extends. As a result, the type errors you've all been getting have surfaced leading to the bad builds.

I've patched this in #828 and once it gets merged we will cut the beta 18 release (likely early tomorrow). Apologies to everyone for the inconvenience. The workaround until then is to downgrade RxJS to v6.2.

**Comment by CaerusKaru** [comment]
Although this issue is fixed, I'm going to reopen it until the new release has been published for visibility.

**Comment by x7even** [comment]
Can confirm and thanks for the quick fix. #828

**Comment by vuthanhvien** [comment]
Thank for this, I still waiting for the the new release has been published

**Comment by bloodymind** [comment]
seems like it not released yet! Any update on this issue please ?

**Comment by sahilt75** [comment]
@bloodymind I updated to rxjs 6.3 and then downgraded again to rxjs 6.0.0. Weird but it worked for me

**Comment by mkginfo** [comment]
@sahilt75, Please share all dependencies and devDependencies

**Comment by CaerusKaru** [comment]
Version 6.0.0-beta.18 has been published on NPM. Please update to resolve this issue.

**Comment by jgeiger-cr** [comment]
With the beta.18 release I now see this error:
ERROR in node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(72,67): error TS1144: '{' or ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,33): error TS1005: ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,39): error TS1109: Expression expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(79,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(80,1): error TS1128: Declaration or statement expected.

**Comment by jrosseel** [comment]
+1. Same issue as jgeiger-cr

**Comment by CaerusKaru** [comment]
Please provide a minimal reproduction, I'm not seeing this on our internal tests. Also please try a clean uninstall/reinstall.

**Comment by jgeiger-cr** [comment]
Sorry, I'm using TS ~2.7.2, Angular ^6.1.6, and already tried a fresh install.

**Comment by dale-french** [comment]
Not sure if it's related to the same issue but I did a clean install with npm instead of Yarn and it built fine

**Comment by CaerusKaru** [comment]
I just installed it successfully on our [StackBlitz](https://stackblitz.com/edit/angular-flex-layout-seed-okj8sj?file=app/test.component.ts) online (tried with both TS 2.7.2 and TS 2.9.2). If you're facing an install/build issue after upgrading, it's likely the install step didn't work correctly.

**Comment by sheariley** [comment]
after updating the version number in package.json the following worked for me:
npm install reinstall @angular/flex-layout

P.S. I kept RXJS @ 6.3.1 and it still worked

**Comment by CaerusKaru** [comment]
Ok I see it now. The `import` syntax is new for TS, and only works with TS 2.9. The workaround is to bump to TS 2.9 as well while we consider options internally.

However, it might be the case that this is the terminal stage in our support for TS 2.7 (ie if you want to use RxJS 6.3, you also need to bump to TS 2.9).

**Comment by jgeiger-cr** [comment]
Excellent, thanks very much for your help.

**Comment by sahilt75** [comment]
@mkginfo 
"dependencies": {
    "@angular/animations": "^6.0.6",
    "@angular/cdk": "^6.2.1",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/flex-layout": "^6.0.0-beta.15",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "^6.2.1",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^6.0.3",
    "@angular-devkit/build-angular": "~0.6.8",
    "typescript": "~2.7.2",
    "@angular/cli": "~6.0.8",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1"
  }

**Comment by Polyterative** [comment]
"However, it might be the case that this is the terminal stage in our support for TS 2.7 (ie if you want to use RxJS 6.3, you also need to bump to TS 2.9)."
So if I am an Angular 6 user (which currently uses Ts 2.7.2) I can only stick with 6.2.2? Correct?

**Comment by CaerusKaru** [comment]
@Polyterative Angular v6.1.x is compatible with TypeScript v2.9

**Comment by Polyterative** [comment]
That's right, found out just now

**Comment by lihaibh** [comment]
@sudiddo it didnt fix the problem for me.
Can you share your package.json file?

**Comment by nigtas** [comment]
Anyone has some other solutions? I am using Angular 6.1.6, rxjs 6.3.1, typescript 2.9.2, flex 6.0.0-beta.18.
Tried all the suggestions from here, cannot make it build on --prod build...

**Comment by sudiddo** [comment]
>  "dependencies": {
    "@angular/animations": "^6.1.6",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.1.6",
    "@angular/compiler": "^6.1.6",
    "@angular/core": "^6.1.6",
    "@angular/flex-layout": "6.0.0-beta.16",
    "@angular/forms": "^6.1.6",
    "@angular/http": "^6.1.6",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "^6.1.6",
    "@angular/platform-browser-dynamic": "^6.1.6",
    "@angular/router": "^6.1.6",
    "@ngrx/store": "^6.1.0",
    "apollo-angular": "^1.1.2",
    "apollo-angular-link-http": "^1.1.1",
    "apollo-cache-inmemory": "^1.2.5",
    "apollo-client": "^2.3.5",
    "apollo-link-context": "^1.0.8",
    "core-js": "^2.5.7",
    "es6-promise": "^4.2.4",
    "graphql": "^14.0.0",
    "graphql-tag": "^2.9.2",
    "hammerjs": "^2.0.8",
    "moment": "^2.22.2",
    "normalize.css": "^8.0.0",
    "promise-polyfill": "^8.1.0",
    "rxjs": "6.2.2",
    "web-animations-js": "^2.3.1",
    "zone.js": "~0.8.26"
  },

this is my dependencies @lihaibh

**Comment by sudiddo** [comment]
@nigtas try to downgrade the rxjs to 6.2.2

**Comment by nigtas** [comment]
@sudiddo Thanks, but did not help...

**Comment by kgish** [comment]
This works for me:

angular 6.1.0
flex-layout: 6.0.0-beta.18
rxjs: 6.3.0
typescript 2.72

**Comment by JoeMellon** [comment]
Quickest fix I did for this was removing current then installing the specific versions of both @angular/flex-layout@6.0.0-beta.16 and rxjs@6.2.2.

**Comment by nigtas** [comment]
@JoeMellon Tried too, but not sure it helps (or some cache left after that many installations).

**Comment by lihaibh** [comment]
what if im using rxjs-compact? should i downgrade it too?

**Comment by rsuk** [comment]
@JoeMellon solution worked for me (thanks) - with the addition for me of un-installing / installing typescript@2.7.2 specifically.

**Comment by MathewBerg** [comment]
Forcing 6.0.0-beta.18 has resolved the issue for me.

**Comment by lihaibh** [comment]
@MathewBerg it shows me the error: node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(72,67): error TS1144: '{' or ';' expected.

**Comment by philgetz** [comment]
Like @jgeiger-cr  I was also this error after updating flex-layout to 6.0.0-beta.18 
```
ERROR in node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(72,67): error TS1144: '{' or ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,33): error TS1005: ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,39): error TS1109: Expression expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(79,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(80,1): error TS1128: Declaration or statement expected.
```

By @CaerusKaru 's suggestion updating Typescript to 2.9 worked for me.

This is my working setup after a clean npm install: 
```
angular: 6.1.4
angular/material: 6.4.6
flex-layout: 6.0.0-beta.18
rxjs: 6.3.0
typescript: 2.9 
```
Peer dependencies might most likely need to be updated.

**Comment by MathewBerg** [comment]
I should add the versions that got a successful build:

```
angular/core: 6.1.6
angular/material: 6.4.7
angular/flex-layout: 6.0.0-beta.18
rxjs: 6.3.2
typescript: 2.9.2
```

**Comment by mazemaker** [comment]
@MathewBerg it helps, thanks.

**Comment by MaximGrischenko** [comment]
@mazemaker Hi, can you take your package.json? i have the same issue, thank you.

**Comment by mazemaker** [comment]
@webmaxru 
...
"dependencies": {
    "@angular/animations": "^6.1.4",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/flex-layout": "^6.0.0-beta.18",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/material": "^6.4.6",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "angular-typewriter": "0.0.15",
    "core-js": "^2.5.4",
    "rxjs": "^6.3.2",
    "typed.js": "^2.0.9",
    "typescript": "^2.9.2",
    "zone.js": "~0.8.26"
  },
...

**Comment by skiabox** [comment]
I can confirm since I am the topic starter that the problem is solved at least for rxjs v6.3.2 and flex-layout v6.0.0-beta.18

**Comment by ngoswald11404** [comment]
"dependencies": {
    "@angular/animations": "6.0.7",
    "@angular/cdk": "^6.0.0",
    "@angular/common": "6.0.7",
    "@angular/compiler": "6.0.7",
    "@angular/core": "6.0.7",
    "@angular/flex-layout": "^6.0.0-beta.16",
    "@angular/forms": "6.0.7",
    "@angular/http": "6.0.7",
    "@angular/material": "^6.0.0",
    "@angular/material-moment-adapter": "^6.3.1",
    "@angular/platform-browser": "6.0.7",
    "@angular/platform-browser-dynamic": "6.0.7",
    "@angular/router": "6.0.7",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "ajv": "^5.5.2",
    "babel-polyfill": "^6.23.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "jspdf": "1.3.5",
    "jspdf-autotable": "2.3.2",
    "moment": "^2.22.2",
    "ngx-quill": "^3.4.0",
    "oidc-client": "^1.3.0",
    "rxjs": "^6.2.1",
    "stickyfilljs": "^2.0.3",
    "typescript": "2.7.2",
    "underscore": "^1.8.3",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.26"
  },

Could anyone tell me why this would get the same error? I have erased cache and node modules. Then I npm installed with some of the changes above, but no luck. Maybe I am missing something?

**Comment by philgetz** [comment]
@ngoswald11404 I am thinking it might be Typescript. Any one correct me if I'm wrong but try to update to 2.9, also typescript is a devDependency install with --save-dev.

**Comment by ngoswald11404** [comment]
@JoeMellon It is fetching from a repository in a cloud, via our company not the node repository. This could be the issue for me. They probably updated our typescript version and it only works in dev because of the package-lock.json so, thanks for the insight!

**Comment by odahcam** [comment]
It is working with `rxjs@^6.3.2` + `@angular/flex-layout@^6.0.0-beta.18`.

**Comment by odahcam** [comment]
@alvipeo It is working with `rxjs@^6.3.2` + `@angular/flex-layout@^6.0.0-beta.18`.

**Comment by waveminded** [comment]
just upgraded still getting the error
`rxjs@^6.3.2`
`@angular/flex-layout@^6.0.0-beta.18`

`ERROR in node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(72,67): error TS1144: '{' or ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,33): error TS1005: ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,39): error TS1109: Expression expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(79,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(80,1): error TS1128: Declaration or statement expected.`

**Comment by mariamtsartsidze** [comment]
How should I rollback rxjs to 6.2.2? I've got 6.3.2. 

> npm install -g rxjs@6.2.2

doesn't change it. Can't find the appropriate command to uninstall and reinstall it. Also one more question, should I do it globally, locally or both ways?

**Comment by mariamtsartsidze** [comment]
The same for me... 

> rxjs@^6.3.2

> angular/flex-layout@^6.0.0-beta.18

Just have got 2.7.2 of typescript instead of 2.9.2 (can it be the reason?), but can't reinstall it. More concretely, I've installed and when I type

> tsc -v

in command line, it shows 2.9.2, but using 

> ng version

 it shows 

> typescript                   2.7.2


 both, globally and locally. If anyone can help, that will be appreciated.

**Comment by waveminded** [comment]
@mariamtsartsidze I changed this version in package.json from 2.7.2 to 2.9.2
`"typescript": "~2.9.2"`
then run `npm install`

**Comment by mariamtsartsidze** [comment]
@waveminded can you compile now?

**Comment by mariamtsartsidze** [comment]
It worked. Now it's compiled successfully. Thanks a lot!

**Comment by pulidovpe** [comment]
I changed typescript from ~2.7.2 to ~2.9.2
then run npm install and it's working for me!

**Comment by Seh83** [comment]
Here are the steps to resolve the issue:

1. Go to package.json, and downgrade the rxjs to the following:  "rxjs": "6.2.2"
2. Delete the node_mouldes folder
3. Run npm install

This should fix the issue; and your project should compile and run again. 

--- Sehul Viras

**Comment by odahcam** [comment]
@Seh83 using the LTS version of both packages shows no problem, a downgrade is not needed anymore.

**Comment by Yaseen-Nadaf** [comment]
This issue is solved in #831

**Comment by pdemilly** [comment]
Not for me. ng -build --prod produce that error

Angular CLI: 6.2.1
Node: 8.9.1
OS: linux x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.1
@angular-devkit/build-angular     0.8.1
@angular-devkit/build-optimizer   0.8.1
@angular-devkit/build-webpack     0.8.1
@angular-devkit/core              0.8.1
@angular-devkit/schematics        0.8.1
@angular/cdk                      6.4.7
@angular/cli                      6.2.1
@angular/fire                     5.0.0
@angular/flex-layout              6.0.0-beta.18
@angular/material                 6.4.7
@ngtools/webpack                  6.2.1
@schematics/angular               0.8.1
@schematics/update                0.8.1
rxjs                              6.3.2
typescript                        2.9.2
webpack                           4.18.1

**Comment by Yaseen-Nadaf** [comment]
Sorry, I don't have any idea about how it works on Linux OS. Did you try
the solution in #831.

**Comment by odahcam** [comment]
Try `ng update --all`

**Comment by bostondevin** [comment]
locking rxjs at 6.6.2 worked for me with everything else up to date (disregarding typescript at 2.9.2 still)

**Comment by codemonkey00** [comment]
I updated from Angular 5 to 6 and can't get flex-layout working. I've been going through this list of versions and can't seem to get a combination that works.  I'm using systemjs and get the error: Unexpected token <  Evaluating .../node_modules/@angular/flex-layout/bundles/flex-layout.umd.js/core .  It works if I bundle it, but not through systemjs.

package.json
`"dependencies": {
    "@angular/animations": "6.1.7",
    "@angular/cdk": "6.4.7",
    "@angular/cli": "1.7.3",
    "@angular/common": "6.1.7",
    "@angular/compiler": "6.1.7",
    "@angular/compiler-cli": "6.1.7",
    "@angular/core": "6.1.7",
    "@angular/flex-layout": "6.0.0-beta.18",
    "@angular/forms": "6.1.7",
    "@angular/http": "6.1.7",
    "@angular/material": "6.4.7",
    "@angular/platform-browser": "6.1.7",
    "@angular/platform-browser-dynamic": "6.1.7",
    "@angular/platform-server": "6.1.7",
    "@angular/router": "6.1.7",
    "@angular/upgrade": "6.1.7",
    "animate.css": "3.7.0",
    "bootstrap": "3.3.7",
    "classlist.js": "1.1.20150312",
    "core-js": "2.5.7",
    "glob": "7.1.2",
    "intl": "1.2.5",
    "jquery": "3.3.1",
    "rxjs": "6.3.2",
    "rxjs-compat": "6.3.2",
    "systemjs": "0.21.4",
    "typescript": "2.9.2",
    "web-animations-js": "2.3.1",
    "zone.js": "0.8.26"
  }`

systemjs.config.js
`(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: 'app',

            // angular bundles
            '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
            '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/common/http': 'npm:@angular/common/bundles/common-http.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/flex-layout': 'npm:@angular/flex-layout/bundles/flex-layout.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            '@angular/material': 'npm:@angular/material/bundles/material.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            "@angular/platform-server": 'npm:@angular/platform-server/bundles/platform-server.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',
            '@angular/upgrade/static': 'npm:@angular/upgrade/bundles/upgrade-static.umd.js',

            //cdk
            '@angular/cdk': 'npm:@angular/cdk/bundles/cdk.umd.js', 
            '@angular/cdk/a11y': 'npm:/@angular/cdk/bundles/cdk-a11y.umd.js',
            '@angular/cdk/accordion': 'npm:/@angular/cdk/bundles/cdk-accordion.umd.js',
            '@angular/cdk/bidi': 'npm:/@angular/cdk/bundles/cdk-bidi.umd.js',
            '@angular/cdk/coercion': 'npm:/@angular/cdk/bundles/cdk-coercion.umd.js',
            '@angular/cdk/collections': 'npm:/@angular/cdk/bundles/cdk-collections.umd.js',
            '@angular/cdk/keycodes': 'npm:/@angular/cdk/bundles/cdk-keycodes.umd.js',
            '@angular/cdk/layout': 'npm:/@angular/cdk/bundles/cdk-layout.umd.js',
            '@angular/cdk/observers': 'npm:/@angular/cdk/bundles/cdk-observers.umd.js',
            '@angular/cdk/overlay': 'npm:/@angular/cdk/bundles/cdk-overlay.umd.js',
            '@angular/cdk/platform': 'npm:/@angular/cdk/bundles/cdk-platform.umd.js',
            '@angular/cdk/portal': 'npm:/@angular/cdk/bundles/cdk-portal.umd.js',
            '@angular/cdk/scrolling': 'npm:/@angular/cdk/bundles/cdk-scrolling.umd.js',
            '@angular/cdk/stepper': 'npm:/@angular/cdk/bundles/cdk-stepper.umd.js',
            '@angular/cdk/table': 'npm:/@angular/cdk/bundles/cdk-table.umd.js',
            '@angular/cdk/text-field': 'npm:/@angular/cdk/bundles/cdk-text-field.umd.js',
            '@angular/cdk/tree': 'npm:/@angular/cdk/bundles/cdk-tree.umd.js',

            'jquery': 'npm:jquery/dist/jquery.js',
            'rxjs': 'npm:rxjs',
            'rxjs/operators': 'npm:rxjs/operators',
            'tslib': 'npm:tslib/tslib.js'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: './main.js', defaultExtension: 'js',
                meta: { './*.js': { loader: 'systemjs-angular-loader.js' } }
            },
            'rxjs': { main: 'index.js', defaultExtension: 'js' },
            'rxjs/operators': { main: 'index.js', defaultExtension: 'js' },
            'jquery': { defaultExtension: 'js' }            
        }
    });
})(this);
`

**Comment by V5NEXT** [comment]
> after updating the version number for flex-layout in package.json, the following worked for me:
> npm install reinstall @angular/flex-layout
> 
> P.S. I kept RXJS @ 6.3.1 and it still worked

Did you replace the version of rxjs@6.3.1 and re-installed it?

**Comment by V5NEXT** [comment]
> I updated from Angular 5 to 6 and can't get flex-layout working. I've been going through this list of versions and can't seem to get a combination that works. I'm using systemjs and get the error: Unexpected token < Evaluating .../node_modules/@angular/flex-layout/bundles/flex-layout.umd.js/core . It works if I bundle it, but not through systemjs.
> 
> package.json
> `"dependencies": { "@angular/animations": "6.1.7", "@angular/cdk": "6.4.7", "@angular/cli": "1.7.3", "@angular/common": "6.1.7", "@angular/compiler": "6.1.7", "@angular/compiler-cli": "6.1.7", "@angular/core": "6.1.7", "@angular/flex-layout": "6.0.0-beta.18", "@angular/forms": "6.1.7", "@angular/http": "6.1.7", "@angular/material": "6.4.7", "@angular/platform-browser": "6.1.7", "@angular/platform-browser-dynamic": "6.1.7", "@angular/platform-server": "6.1.7", "@angular/router": "6.1.7", "@angular/upgrade": "6.1.7", "animate.css": "3.7.0", "bootstrap": "3.3.7", "classlist.js": "1.1.20150312", "core-js": "2.5.7", "glob": "7.1.2", "intl": "1.2.5", "jquery": "3.3.1", "rxjs": "6.3.2", "rxjs-compat": "6.3.2", "systemjs": "0.21.4", "typescript": "2.9.2", "web-animations-js": "2.3.1", "zone.js": "0.8.26" }`
> 
> systemjs.config.js
> `(function (global) {
> System.config({
> paths: {
> // paths serve as alias
> 'npm:': 'node_modules/'
> },
> // map tells the System loader where to look for things
> map: {
> // our app is within the app folder
> app: 'app',
> 
> ```
>         // angular bundles
>         '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
>         '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
>         '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
>         '@angular/common/http': 'npm:@angular/common/bundles/common-http.umd.js',
>         '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
>         '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
>         '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
>         '@angular/flex-layout': 'npm:@angular/flex-layout/bundles/flex-layout.umd.js',
>         '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
>         '@angular/material': 'npm:@angular/material/bundles/material.umd.js',
>         '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
>         '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',
>         '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
>         "@angular/platform-server": 'npm:@angular/platform-server/bundles/platform-server.umd.js',
>         '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
>         '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',
>         '@angular/upgrade/static': 'npm:@angular/upgrade/bundles/upgrade-static.umd.js',
> 
>         //cdk
>         '@angular/cdk': 'npm:@angular/cdk/bundles/cdk.umd.js', 
>         '@angular/cdk/a11y': 'npm:/@angular/cdk/bundles/cdk-a11y.umd.js',
>         '@angular/cdk/accordion': 'npm:/@angular/cdk/bundles/cdk-accordion.umd.js',
>         '@angular/cdk/bidi': 'npm:/@angular/cdk/bundles/cdk-bidi.umd.js',
>         '@angular/cdk/coercion': 'npm:/@angular/cdk/bundles/cdk-coercion.umd.js',
>         '@angular/cdk/collections': 'npm:/@angular/cdk/bundles/cdk-collections.umd.js',
>         '@angular/cdk/keycodes': 'npm:/@angular/cdk/bundles/cdk-keycodes.umd.js',
>         '@angular/cdk/layout': 'npm:/@angular/cdk/bundles/cdk-layout.umd.js',
>         '@angular/cdk/observers': 'npm:/@angular/cdk/bundles/cdk-observers.umd.js',
>         '@angular/cdk/overlay': 'npm:/@angular/cdk/bundles/cdk-overlay.umd.js',
>         '@angular/cdk/platform': 'npm:/@angular/cdk/bundles/cdk-platform.umd.js',
>         '@angular/cdk/portal': 'npm:/@angular/cdk/bundles/cdk-portal.umd.js',
>         '@angular/cdk/scrolling': 'npm:/@angular/cdk/bundles/cdk-scrolling.umd.js',
>         '@angular/cdk/stepper': 'npm:/@angular/cdk/bundles/cdk-stepper.umd.js',
>         '@angular/cdk/table': 'npm:/@angular/cdk/bundles/cdk-table.umd.js',
>         '@angular/cdk/text-field': 'npm:/@angular/cdk/bundles/cdk-text-field.umd.js',
>         '@angular/cdk/tree': 'npm:/@angular/cdk/bundles/cdk-tree.umd.js',
> 
>         'jquery': 'npm:jquery/dist/jquery.js',
>         'rxjs': 'npm:rxjs',
>         'rxjs/operators': 'npm:rxjs/operators',
>         'tslib': 'npm:tslib/tslib.js'
>     },
>     // packages tells the System loader how to load when no filename and/or no extension
>     packages: {
>         app: {
>             main: './main.js', defaultExtension: 'js',
>             meta: { './*.js': { loader: 'systemjs-angular-loader.js' } }
>         },
>         'rxjs': { main: 'index.js', defaultExtension: 'js' },
>         'rxjs/operators': { main: 'index.js', defaultExtension: 'js' },
>         'jquery': { defaultExtension: 'js' }            
>     }
> });
> ```
> 
> })(this);
> `

I manually changed the typescript version in angular.json file to 2.9.2 and run npm install, it fixed me the issue. May be it was with the TS version.

**Comment by heavyrick** [comment]
i had the same issue, so i uninstalled version 6.0.0-beta.18 and install de version 6.0.0-beta.16 and solve the problem o/

**Comment by Twechy** [comment]
@alvipeo It is working with rxjs@^6.3.2 + @angular/flex-layout@^6.0.0-beta.18.

**Comment by maytanthegeek** [comment]
Works for me with following versions on Arch:
`@angular/flex-layout: ^6.0.0-beta.18`
`rxjs: ^6.3.3`
`typescript: ~2.9.2`

Thanks for the help everyone.

**Comment by germfy** [comment]
For me it worked on MacOS:
`@angular/flex-layout: 6.0.0-beta.18`
`RxJS: 6.3.2`
`typescript: 2.9.2`

**Comment by whitewaves** [comment]
@alvipeo 
is it with current version of angular

**Comment by anasanzari** [comment]
+1

**Comment by Polyterative** [comment]
I was on flex 15 before, now the 18 compiles but my layouts are mostrly broken and wrong. Is this my fault?  I need to fix everything by hand?

**Comment by Koesters** [comment]
typescript: ~2.9.2
    "@angular/animations": "^6.1.10",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.1.10",
    "@angular/compiler": "^6.1.10",
    "@angular/core": "^6.1.10",
    "@angular/flex-layout": "^7.0.0-beta.19",
    "@angular/forms": "^6.1.10",
    "@angular/http": "^6.1.10",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "^6.1.10",
    "@angular/platform-browser-dynamic": "^6.1.10",
    "@angular/router": "^6.1.10",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.1.0",

Windows 10 under cmder worked for me 
ricardosaracino solution compiled but threw the errors in the browser (Chrome),

I then tried npm install rxjs-compat@latest

and then it broke again. 

I had then to do 

npm install rxjs-compat@6.1.0

and downgrade flexlayout again to 

npm install @angular/flex-layout@6.0.0-beta.18

"@angular/flex-layout": "^7.0.0-beta.19", remains now a no go area

I run Cesium in angular the procedure leaves me with a 90% Frame rate loss on Dual Titan Maxwell.  From 60 fps to 6.

Deleting two mat tables increases the performance.

**Comment by eyho** [comment]
> I was on flex 15 before, now the 18 compiles but my layouts are mostrly broken and wrong. Is this my fault? Do I need to fix everything by hand?

Same happened to me this afternoon. Should I just put everything back to beta.15 and wait for a long term fix, what do you think?

**Comment by CaerusKaru** [comment]
Now that it's been a good three weeks since this has cropped up, I'm going to close this issue. I hope it helped everyone who came across it resolve any issues with their app.

I'd also like to apologize to those people who ran into issues repeatedly, I know this hurts the user experience and is not ideal. In the future, we'll probably look into scoping TypeScript version distributions in package.json, but this may be a little ways out in terms of development.

**Comment by Polyterative** [comment]
> > I was on flex 15 before, now the 18 compiles but my layouts are mostrly broken and wrong. Is this my fault? Do I need to fix everything by hand?
> 
> Same happened to me this afternoon. Should I just put everything back to beta.15 and wait for a long term fix, what do you think?
> 
> Using 6.2.2 rxjs with ~2.9.2 TS and 6.0.0-beta.15 flex-layout solves the error and the broken layout also.

I guess this is what we should expect from a _beta_

**Comment by dhantoot** [comment]
> For me it worked on MacOS:
> `@angular/flex-layout: 6.0.0-beta.18`
> `RxJS: 6.3.2`
> `typescript: 2.9.2`

this worked for me too !

**Comment by malinka007** [comment]
Flex-layout  in versions 7.0.0-beta.20 and higher replaced ObservableMedia  with MediaObserver.

"media-observer: ObservableMedia is now deprecated in anticipation of RxJS v7. The new API is called MediaObserver, and provides the exact same functionality as ObservableMedia, except you cannot directly subscribe to it,
Developers should subscribe to MediaObserver's media$ property; in place of subscribing directly to ObservableMedia." taken from https://github.com/angular/flex-layout/blob/master/CHANGELOG.

After I made that change, it worked with no issues on the latest versions as of today: 
"@angular/core": "^7.1.1",
"@angular/flex-layout": "^7.0.0-beta.23",
"rxjs": "^6.3.3",
"rxjs-compat": "^6.3.3",
